# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('casenumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('staus', models.CharField(max_length=120)),
                ('courtname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaintid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dateofcomplaint', models.DateTimeField()),
                ('dateofincident', models.DateTimeField()),
                ('description', models.TextField()),
                ('policestation', models.CharField(max_length=120)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fir',
            fields=[
                ('firid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('signedby', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idnumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
