# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('casenumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('courtname', models.CharField(max_length=200)),
                ('verdict', models.TextField()),
                ('caseflag', models.BooleanField()),
                ('dateofregister', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CopStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateofregister', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='fir',
            name='content',
            field=models.TextField(default='First Information Report'),
        ),
    ]
