# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0003_auto_20160414_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='dateofincident',
        ),
    ]
