# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0004_remove_complaint_dateofincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaintid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
