# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimefiles', '0005_auto_20160414_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='complaintid',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='crimefiles.Complaint'),
        ),
    ]
