# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
